### ISSUE TITLE
Screenshot or demo?

### ISSUE THREAD

**Issue by colindean** [kyoung/unconf#5]
I'd love to see what this looks like without having to set it up. A couple of screenshots or a minute-long demo video would probably suffice.

**Comment by colindean** [comment]
(I'm half-volunteering to do this, but writing it down in case someone else can get to it before I can.)

**Comment by kyoung** [comment]
I think I can manage that! Give me a few days to get it together?

**Comment by colindean** [comment]
sure!

**Comment by kyoung** [comment]
@colindean I've added some screenshots to the readme. Apologies for the giant size; apparently github markdown doesn't let you size images? I'll try and get around to resizing them myself later, but for now, that should showcase what the user experience is.

**Comment by colindean** [comment]
Good enough for my purposes!
